### PR TITLE
feat: abstract node pools out of gcp-gke component module

### PR DESCRIPTION
**Pull request by JoseFMP**
## Pull Request Submission Checklist

Please confirm that you have done the following before requesting reviews:

- [x] I have confirmed that the PR type is appropriate for the change I am making according to the [Honest Pull Request and Commit Message Naming Conventions](https://www.notion.so/honestbank/Pull-Request-and-Commit-Message-Naming-Conventions-bd97f2cbb34c4c73b1ff3a3e384b850c).
- [x] I have typed an adequate description that explains **why** I am making this change.
- [x] I have installed and run standard pre-commit hooks that lints and validates my code.

### Description
Currently the `gcp-gke` component module creates a node pool named 'primary' and does not provide a way to configure other node pools within the module.
The goal of this PR if to make it possible to configure multiple node pools, with different configuration each, when using the `gcp-gke` module.

What this PR does:
* Creates a Terraform component module named `gcp-gke-node-pool` inside the `gcp-gke` component. This component is to be used only within the `gcp-gke` component and therefore is in the `modules` folder of `gcp-gke`
* In `gcp-gke` componet, the 'primary` node pool is removed.
* In `gcp-gke` component, a new input named `node_pools` is added. It is a list of the node pools to be created, each of them being defined by its name, machine type, and number of nodes (see code for detail).
* Inside `gcp-gke`, the new input `node_pools` is iterated in order to create the node pools, using `gcp-gke-node-pool` component.

- - -
This change is [Reviewable](https://reviewable.io/reviews/honestbank/terraform-gcp-gke/82)

### CODE REVIEW

**Review by jai — CHANGES_REQUESTED** [review]
> Reviewed 3 of 17 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/honestbank/terraform-gcp-gke/82)* status: 3 of 17 files reviewed, 1 unresolved discussion (waiting on @JoseFMP and @poom)

___
*[`main.tf` line 48 at r1](https://reviewable.io/reviews/honestbank/terraform-gcp-gke/82#-NH8vI_8AroU2jNFMvg0:-NH8vI_8AroU2jNFMvg1:b-kpbfc2) ([raw file](https://github.com/honestbank/terraform-gcp-gke/blob/e1baf23399f5150b9fa05133679e8cb7cf089d2f/main.tf#L48)):*
> ```HCL
>       minimum_node_count = var.minimum_node_count
>       maximum_node_count = var.maximum_node_count
>       tags               = ["terratest"]
> ```

we're sure we want to tag this as `terratest` right from here/hardcoded? Why not pass in the tags from the terratest Go file?

**Review by JoseFMP — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/honestbank/terraform-gcp-gke/82)* status: 3 of 17 files reviewed, 1 unresolved discussion (waiting on @jai and @poom)

___
*[`main.tf` line 48 at r1](https://reviewable.io/reviews/honestbank/terraform-gcp-gke/82#-NH8vI_8AroU2jNFMvg0:-NH99JygDxi6auzg1EmU:b2qa4ab) ([raw file](https://github.com/honestbank/terraform-gcp-gke/blob/e1baf23399f5150b9fa05133679e8cb7cf089d2f/main.tf#L48)):*
<details><summary><i>Previously, jai (Jai Govindani) wrote…</i></summary><blockquote>

we're sure we want to tag this as `terratest` right from here/hardcoded? Why not pass in the tags from the terratest Go file?
</blockquote></details>

@jai this file is not used in the Terratest.
I was a bit confused myself. So these terraform files are not really used in the terratest, see `gke_test.go` line 93. The only effect these in the root of the repository have is to verify 'terraform init' and 'terraform plan' do work.

So still I can make it a variable and put there the value of a variable. But I would need to revamp the terratest in order to use these files in the root of the repo.

**Review by jai — APPROVED** [review]
> Reviewed 14 of 17 files at r1.
> *[Reviewable](https://reviewable.io/reviews/honestbank/terraform-gcp-gke/82)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @poom)

**Comment by jai** [comment]
I think we need to make this non-breaking @JoseFMP currently it seems to be a breaking change because it requires consumers to add `node_pools` property.

I think we should not break the current infra - meaning the current node pool should be returned as-is, and we should instead allow adding supplementary node pools through an optional variable.

**Pull request closed without merging**
